/*
 * This source file was generated by the Gradle 'init' task
 */
package io.awijaya;

import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    public void test() {
        System.out.println("test");
    }

    @Test void appHasAGreeting() {
        AppTest appTest = new AppTest();
        appTest.test();

    }
}
